### ISSUE TITLE
NetworkException: Unable to read from stream

### ISSUE THREAD

**Issue by OneAceGuy** [mstilkerich/rcmcarddav#333]
### Background
Roundcube 1.4.3
carddav v4.0.4
Ubuntu 20.04 (focal)
Nextcloud 20.0.6 (contacts maintained here)
_Note: Roundcube and Nextcloud are on different servers_
_Note: rcmcarddav installed manually, __not__ using Composer_

### Details
I am stumped. I have 640+ contacts managed in Nextcloud that I want to sync with Roundcube. The connection works, the address books are synced, I can see the definitions in the `carddav_addressbooks` table in the database; but when syncing or trying to pull in the contacts Roundcube shows a 'Loading...' message at the bottom of the screen for several minutes, then just stops. The logs at `/var/log/roundcube/carddav.log` show the following: 
```
02-Feb-2021 11:12:18 -0800]: <ecqkudij> sync-collection REPORT produced exception {"exception":{}}
[02-Feb-2021 11:12:18 -0800]: <ecqkudij> sync-collection REPORT produced exception {"exception":{}}
[02-Feb-2021 11:14:19 -0800]: <ecqkudij> Errors occurred during the refresh of addressbook 7: RuntimeException: Unable to read from stream in /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/psr7/src/Stream.php:230
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/psr7/src/Utils.php(53): GuzzleHttp\Psr7\Stream->read()
#1 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(200): GuzzleHttp\Psr7\Utils::copyToStream()
#2 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(130): GuzzleHttp\Handler\StreamHandler->drain()
#3 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(56): GuzzleHttp\Handler\StreamHandler->createResponse()
#4 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(201): GuzzleHttp\Handler\StreamHandler->__invoke()
#5 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#6 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#11 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
#12 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()
#13 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php(124): GuzzleHttp\Client->request()
#14 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(409): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->sendRequest()
#15 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(311): MStilkerich\CardDavClient\CardDavClient->requestWithRedirectionTarget()
#16 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(237): MStilkerich\CardDavClient\CardDavClient->findProperties()
#17 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(123): MStilkerich\CardDavClient\Services\Sync->determineChangesViaETags()
#18 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(59): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch()
#19 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(1220): MStilkerich\CardDavClient\Services\Sync->synchronize()
#20 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(179): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#21 /usr/share/roundcube/plugins/carddav/carddav.php(329): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->__construct()
#22 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(441): carddav->getAddressbook()
#23 /usr/share/roundcube/program/include/rcmail.php(226): rcube_plugin_api->exec_hook()
#24 /usr/share/roundcube/program/steps/mail/autocomplete.inc(67): rcmail->get_address_book()
#25 /usr/share/roundcube/index.php(302): include_once('/usr/share/roun...')
#26 {main}

Next GuzzleHttp\Exception\RequestException: Unable to read from stream in /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:52
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(74): GuzzleHttp\Exception\RequestException::wrapException()
#1 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(201): GuzzleHttp\Handler\StreamHandler->__invoke()
#2 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#3 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#4 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#5 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\RedirectMiddleware->__invoke()
#6 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#7 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#8 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
#9 /usr/share/roundcube/plugins/carddav/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()
#10 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php(124): GuzzleHttp\Client->request()
#11 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(409): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->sendRequest()
#12 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(311): MStilkerich\CardDavClient\CardDavClient->requestWithRedirectionTarget()
#13 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(237): MStilkerich\CardDavClient\CardDavClient->findProperties()
#14 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(123): MStilkerich\CardDavClient\Services\Sync->determineChangesViaETags()
#15 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(59): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch()
#16 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(1220): MStilkerich\CardDavClient\Services\Sync->synchronize()
#17 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(179): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#18 /usr/share/roundcube/plugins/carddav/carddav.php(329): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->__construct()
#19 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(441): carddav->getAddressbook()
#20 /usr/share/roundcube/program/include/rcmail.php(226): rcube_plugin_api->exec_hook()
#21 /usr/share/roundcube/program/steps/mail/autocomplete.inc(67): rcmail->get_address_book()
#22 /usr/share/roundcube/index.php(302): include_once('/usr/share/roun...')
#23 {main}

Next MStilkerich\CardDavClient\Exception\NetworkException: Unable to read from stream in /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php:158
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(409): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->sendRequest()
#1 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/CardDavClient.php(311): MStilkerich\CardDavClient\CardDavClient->requestWithRedirectionTarget()
#2 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(237): MStilkerich\CardDavClient\CardDavClient->findProperties()
#3 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(123): MStilkerich\CardDavClient\Services\Sync->determineChangesViaETags()
#4 /usr/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Services/Sync.php(59): MStilkerich\CardDavClient\Services\Sync->synchronizeOneBatch()
#5 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(1220): MStilkerich\CardDavClient\Services\Sync->synchronize()
#6 /usr/share/roundcube/plugins/carddav/src/Addressbook.php(179): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->resync()
#7 /usr/share/roundcube/plugins/carddav/carddav.php(329): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->__construct()
#8 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(441): carddav->getAddressbook()
#9 /usr/share/roundcube/program/include/rcmail.php(226): rcube_plugin_api->exec_hook()
#10 /usr/share/roundcube/program/steps/mail/autocomplete.inc(67): rcmail->get_address_book()
#11 /usr/share/roundcube/index.php(302): include_once('/usr/share/roun...')
#12 {main}
```
The http log at `/var/log/roundcube/carddav_http.log` shows the following: 
```
--------
Unable to read from stream
[02-Feb-2021 11:14:19 -0800]: <ecqkudij> "PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1" NULL
>>>>>>>>
PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1
Content-Length: 236
User-Agent: GuzzleHttp/7
Authorization: --- REDACTED BY MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger ---
Host: nextcloud.<mydomainremoved>.net
Depth: 1
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <CS:getctag/>
  <DAV:getetag/>
  <DAV:sync-token/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<
```
Is this a perms issue on the filesystem? If so where do I make changes, and what changes would I make? Is this a code issue? What else might the issue be? Any ideas will be extremely helpful. If you need additional info let me know. Thanks.

**Comment by OneAceGuy** [comment]
@mstilkerich I just saw some potentially pertinent information in your comments for issue https://github.com/mstilkerich/rcmcarddav/issues/293#issuecomment-660152960 .

I will do some investigating on my Roundcube server to see if this is an issue related to Composer actions (running v1.10.1). I followed the instructions from your [Install guide](https://github.com/mstilkerich/rcmcarddav/blob/master/doc/INSTALL.md) for Debian/Ubuntu, and ran Composer from the `/var/lib/roundcube/plugins` directory as instructed, but being the crazy "roundcube is in 3 places" (`/var/lib/`, `/usr/share/`, and `/etc/roundcube/`) for Debian-based builds, it is likely something is not correct. 

That said, please let me know if you see something else I can go after to fix. Thanks.

**Comment by mstilkerich** [comment]
Hello,

  thanks for that detailed issue report. It is an exception triggered in the lower-level HTTP client library. I am not able to tell you what the problem is, so unfortunately I cannot give you a solution. But a few things to try...

- Why do you think it has something to do with filesystem permissions? I cannot see a relation.
- I also don't think it is related to your manual installation, at least I don't see anything in the logs in the direction.
- Do you have the PHP curl extension installed? It should work without, but it is a more common setup to have it. So if not, please try installing the php-curl package. You might need to reload you webserver or php-fpm process for it to get used.
- The connection works in general if the discovery works. So maybe the problem is related to your large addressbook. Can you try with a smaller addressbook? You can create an additional addressbook in Nextcloud (it allows multiple addressbooks per user) and then try to sync that. You can deactivate the large one in the carddav settings to avoid it to be synced.
- Can you please post the full HTTP log of a sync? A log entry always starts with the line containing the date and ends with a line of `--------`. You can filter by date to get all entries for the sync operation, or simply delete the http log before doing the sync.
- To trigger a sync manually, you can use the corresponding checkbox in the carddav settings and hit the save button.
- Have you checked the logs of the nextcloud servers for errors?

**Comment by OneAceGuy** [comment]
Michael - thanks for the quick response, you provided PERFECT feedback! The issue was the mssing PHP curl extension. I installed, enabled, and restarted the webserver and everything works perfect now. The sync took 2 seconds and all contacts are available now. 

To answer your questions:
-  regarding perms, I was going down the line of thinking that maybe there was some temp files being written or some caching going on... I admit I did not look at the source to verify, just trying to figure out why the problem was occurring (it was late and I was grasping for straws!)
- I checked Composer manual install, did not see anything unusual, but your write up in the comments really helped me investigate - thanks
- Because you asked, here is the full HTTP log for your review. As you will see I have two address books to sync, one called Business, the other called Home:
```
[02-Feb-2021 11:12:18 -0800]: <ecqkudij> "REPORT /remote.php/dav/addressbooks/users/<myloginremoved>/business/ HTTP/1.1" NULL
>>>>>>>>
REPORT /remote.php/dav/addressbooks/users/<myloginremoved>/business/ HTTP/1.1
Content-Length: 285
User-Agent: GuzzleHttp/7
Authorization: --- REDACTED BY MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger ---
Host: nextcloud.<mydomainremoved>.net
Depth: 0
Content-Type: application/xml; charset=UTF-8

<?xml version="1.0"?>
<DAV:sync-collection xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:sync-token></DAV:sync-token>
 <DAV:sync-level>1</DAV:sync-level>
 <DAV:prop>
  <DAV:getetag/>
 </DAV:prop>
</DAV:sync-collection>

<<<<<<<<

--------
Unable to read from stream
[02-Feb-2021 11:12:18 -0800]: <ecqkudij> "REPORT /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1" NULL
>>>>>>>>
REPORT /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1
Content-Length: 285
User-Agent: GuzzleHttp/7
Authorization: --- REDACTED BY MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger ---
Host: nextcloud.<mydomainremoved>.net
Depth: 0
Content-Type: application/xml; charset=UTF-8

<?xml version="1.0"?>
<DAV:sync-collection xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:sync-token></DAV:sync-token>
 <DAV:sync-level>1</DAV:sync-level>
 <DAV:prop>
  <DAV:getetag/>
 </DAV:prop>
</DAV:sync-collection>

<<<<<<<<

--------
Unable to read from stream
[02-Feb-2021 11:14:19 -0800]: <ecqkudij> "PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/business/ HTTP/1.1" NULL
>>>>>>>>
PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/business/ HTTP/1.1
Content-Length: 236
User-Agent: GuzzleHttp/7
Authorization: --- REDACTED BY MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger ---
Host: nextcloud.<mydomainremoved>.net
Depth: 1
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <CS:getctag/>
  <DAV:getetag/>
  <DAV:sync-token/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<

--------
Unable to read from stream
[02-Feb-2021 11:14:19 -0800]: <ecqkudij> "PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1" NULL
>>>>>>>>
PROPFIND /remote.php/dav/addressbooks/users/<myloginremoved>/home/ HTTP/1.1
Content-Length: 236
User-Agent: GuzzleHttp/7
Authorization: --- REDACTED BY MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger ---
Host: nextcloud.<mydomainremoved>.net
Depth: 1
Content-Type: application/xml; charset=UTF-8
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <CS:getctag/>
  <DAV:getetag/>
  <DAV:sync-token/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<

--------
Unable to read from stream
```
- Regarding nextcloud logs, I did not see anything specific to DAV failures, but I admit my logs are a mess... the upgrade to Nextcloud 20 enabled debug mode on my logs (which I was not aware of until now) and they are flooded with `/appinfo/app.php is deprecated` messages, along with tons of other info. At any rate, nothing showed around the same time as the carddav log entries.

Thanks again for the assistance, great work on the plugin.
