### ISSUE TITLE
Array given to Account constructor instead of string

### ISSUE THREAD

**Issue by triaxx** [mstilkerich/rcmcarddav#387]
I get the following error message for Roundcube 1.5.2 and PHP 7.4.30:
```
2022-07-14T16:33:02.983532+00:00 roundcube - - - PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MStilkerich\CardDavClient\Account::__construct() must be of the type string, array given, called in /usr/pkg/share/roundcube/plugins/carddav/src/Config.php on line 161 and defined in /usr/pkg/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Account.php:83
2022-07-14T16:33:02.983642+00:00 roundcube - - - Stack trace:
2022-07-14T16:33:02.983689+00:00 roundcube - - - #0 /usr/pkg/share/roundcube/plugins/carddav/src/Config.php(161): MStilkerich\CardDavClient\Account->__construct('https://dav.exa...', Array, '', 'https://dav.exa...')
2022-07-14T16:33:02.983733+00:00 roundcube - - - #1 /usr/pkg/share/roundcube/plugins/carddav/src/Addressbook.php(1617): MStilkerich\CardDavAddressbook4Roundcube\Config::makeAccount('https://dav.exa...', 'user', 'passwd', 'https://dav.exa...')
2022-07-14T16:33:02.983776+00:00 roundcube - - - #2 /usr/pkg/share/roundcube/plugins/carddav/src/Addressbook.php(425): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->getCardDavObj()
2022-07-14T16:33:02.983822+00:00 roundcube - - - #3 /usr/pkg/share/roundcube/program/actions/contacts/show.php(47): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->get_record('2746', true)
2022-07-14T16:33:02.983865+00:00 roundcube - - - #4 /usr/pkg/share/roundcube/program/include in /usr/pkg/share/roundcube/plugins/carddav/vendor/mstilkerich/carddavclient/src/Account.php on line 83
```

**Comment by mstilkerich** [comment]
Your version of mstilkerich\carddavclient is too old, please update using composer. See #370 

Our of curiosity, because this issue should not occur when following the install instructions: How did you install rcmcarddav?

**Comment by triaxx** [comment]
I install rcmcarddav with `composer install --no-dev`

**Comment by mstilkerich** [comment]
There appears to be a vendor directory below plugins/carddav with the old version of carddavclient. There is no vendor directory supposed to be at that location if you install using composer, running composer in the roundcube main directory.

Anyway, I suggest you delete the plugins/carddav/vendor directory. If you installed using composer in the roundcube main dir, the correct dependencies will be there. Otherwise run composer in the main dir as written in the INSTALL.md file and it will pull the correct dependencies.

**Comment by mstilkerich** [comment]
Yes, the dependencies in the release tarballs work for the rcmcarddav release they are shipped with. There is potential for conflict when roundcube and rcmcarddav use the same libs which can then exist in different versions in the two vendor directories. The latest version of rcmcarddav does its best to minimize such risk.
