### ISSUE TITLE
Error: Undefined constant in HttpClientAdapterGuzzle.php:106

### ISSUE THREAD

**Issue by Pantos** [mstilkerich/rcmcarddav#389]
I installed Roundcube 1.6 today. After that I ran `composer update --no-dev`. First I ran into the issue  #388. I removed the plugin and installed it again. The plugin seems to working now.

But If I want to look into an address I get an `500 Internal Server Error` now. The Roundcube error.log shows:

```
30-Jul-2022 18:36:00 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "MStilkerich\CardDavClient\CURLAUTH_NEGOTIATE" in /html/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php:106
Stack trace:
#0 /html/vendor/mstilkerich/carddavclient/src/CardDavClient.php(58): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->__construct('https://cloud.tes...', Array)
#1 /html/vendor/mstilkerich/carddavclient/src/Account.php(143): MStilkerich\CardDavClient\CardDavClient->__construct('https://cloud.tes...', Array)
#2 /html/vendor/mstilkerich/carddavclient/src/Account.php(216): MStilkerich\CardDavClient\Account->getClient()
#3 /html/vendor/mstilkerich/carddavclient/src/Services/Discovery.php(120): MStilkerich\CardDavClient\Account->findCurrentUserPrincipal('/.well-known/ca...')
#4 /html/plugins/carddav/carddav.php(1507): MStilkerich\CardDavClient\Services\Discovery->discoverAddressbooks(Object(MStilkerich\CardDavClient\Account))
#5 /html/plugins/carddav/carddav.php(630): carddav->determineAddressbooksToAdd(Object(MStilkerich\CardDavClient\Account))
#6 /html/program/lib/Roundcube/rcube_plugin_api.php(518): carddav->savePreferences(Array)
#7 /html/program/actions/settings/prefs_save.php(165): rcube_plugin_api->exec_hook('preferences_sav...', Array)
#8 /html/program/include/rcmail.php(275): rcmail_action_settings_prefs_save->run(Array)
#9 /html/index.php(278): rcmail->action_handler()
#10 {main}
  thrown in /html/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php on line 106
  thrown in /html/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php on line 106
```
Has someone else the same problem? Is it a general bug or an individual problem? Any idea how to solve it?

**Comment by mstilkerich** [comment]
Can you check if the reason is a very old curl library, see mstilkerich/carddavclient#17

**Comment by Pantos** [comment]
I'm using PHP 8.0.21 and `curl -V` says:

```
curl 7.83.1 (x86_64-pc-linux-gnu) libcurl/7.83.1 OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.7 libidn2/2.3.3 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.10.0 nghttp2/1.33.0 OpenLDAP/2.4.44
Release-Date: 2022-05-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL UnixSockets
```

**Comment by mstilkerich** [comment]
Hmm, that‘s not it then. Do you have the php curl extension installed? You can run `php -m` to check

**Comment by Pantos** [comment]
PHP curl extension is installed.

The carddavclient version is:

```
...
roundcube/carddav             v4.4.2   CardDAV adapter for connecting to CardDAV-enabled addressbooks
roundcube/plugin-installer    0.3.2    A composer-installer for Roundcube plugins and skins.
...
```
It's hosted at uberspace.de
